name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:

  build:
    name: dl-cpu
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macOS-10.15]  # windows-2019,
        python-version: [3.6, 3.7, 3.8]
        requirements: ['latest', 'minimal']
        exclude:
          # pickle problems
          - python-version: 3.8
            os: macOS-10.15
          - python-version: 3.6
            os: macOS-10.15

    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2

      - name: set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # https://github.com/pytorch/pytorch/issues/20030
      - name: Setup macOS
        if: startsWith(runner.os, 'macOS')
        run: |
          brew install libomp
          brew install gnu-sed

      - name: set minimal dependencies
        if: matrix.requirements == 'minimal'
        run: |
          python -c "req = open('./requirements/requirements.txt').read().replace('>', '=') ; open('./requirements/requirements.txt', 'w').write(req)"

      - name: install dependencies
        run: |
          # python -m pip install --upgrade --user pip
          pip install -r ./requirements/requirements.txt -r ./requirements/requirements-dev.txt
          python --version
          pip --version
          pip list
        shell: bash

      - name: check examples
        env:
          REQUIREMENTS: ${{ matrix.requirements }}
        run: |
          pytest .
